image: golang:1.7
stages:
  - test
  - build

variables:
  CGO_ENABLED: 0 # https://github.com/alecthomas/gometalinter/issues/149
  GIN_MODE: release

before_script:
  - go get github.com/tools/godep
  - ln -s /builds $GOPATH/src/gitlab.com
  - cd $GOPATH/src/gitlab.com/MikaXII/recalbox-api
  - godep restore

test-lint:
  stage: test
  when: manual
  script:
    - go get -u github.com/alecthomas/gometalinter
    - gometalinter --install
    - gometalinter --aggregate ./... --disable gotype 
    - go test

build-api:
  stage: build
  when: manual
  script:
    - go build