image: golang:1.7
stages:
  - build

before_script:
  - go get github.com/tools/godep
  - ln -s /builds /go/src/gitlab.com
  - cd /go/src/gitlab.com/MikaXII/recalbox-api

build-api:
  stage: build
  when: manual
  script:
    - godep restore
    - go build