image: golang:1.7
stages:
  - lint
  - build

variables:
  CGO_ENABLED: 0 # https://github.com/alecthomas/gometalinter/issues/149

before_script:
  - go get github.com/tools/godep
  - go get -u github.com/alecthomas/gometalinter
  - gometalinter --install
  - ln -s /builds $GOPATH/src/gitlab.com

golinter:
  stage: lint
  when: manual
  script:
    - cd $GOPATH/src/gitlab.com/MikaXII/recalbox-api
    - godep restore
    - gometalinter --aggregate ./... --disable gotype 

build-api:
  stage: build
  when: manual
  script:
    - go build