image: golang:1.7
stages:
  - build

before_script:
  - go get github.com/kardianos/govendor
  - ln -s /builds /go/src/gitlab.com
  - cd /go/src/gitlab.com/MikaXII/recalbox-api

build-my-project:
  stage: build
  script:
    - govendor sync
    - go build