version= "0.0.1"

[fs]
systemsPath= "/recalbox/share/roms/"
biosPath= "/recalbox/share/bios/"
gamelist= "/gamelist.txt"
recalboxConf = "/recalbox/share/system/recalbox.conf"

[listEndpoint]
systemsEndpoint= "/systems"
biosEndpoint= "/bios"
